
<div class="row">
    <div class="col col-8">
        <div class="panel">
            <div class="panel-header">
                DBI Data Synchronisation
                <button id="btnDataSync" type="submit" class="primary pull-right">Sync Data</button>
            </div>
            <div id="synclog" class="panel-content"></div>
        </div>
    </div>
    <div class="col col-4">
        <?=$this->partial('version_info', $this->version_info);?>
    </div>
</div>

