
<div class="panel default">
    <div class="panel-header">Current version</div>
    <div class="panel-content">
        <div class="row">
            <?=$this->current;?>
        </div>
        <?php
        if(($count = count($this->updates)) > 0)
            echo $this->html->div('Update' . (($count > 1) ? 's': '') . ' available')->class('label warning');
        else
            echo $this->html->div('Up to date')->class('label success');
        ?>

    </div>
</div>
