
<div class="panel default flex-grow-1">
    <div class="panel-header">Current version</div>
    <div class="panel-content">
        <div class="row">
            <?=$this->current;?>
        </div>
        <?php
        if($this->latest)
            echo $this->html->div('Up to date')->class('label success');
        else
            echo $this->html->div('Update available')->class('label warning');
        ?>

    </div>
</div>
